### ISSUE TITLE
Can't use sub-naming standard as it expects primary name to pass an argument

### ISSUE THREAD

**Issue by daryn-staxo** [dgoring/laravel-inherit-resource#1]
When creating a route resource
```php
Route::resource('products', 'Admin\ProductsController');
```
all works fine.

When attempting to group that same resource under, for instance, the 'admin' namespace, i.e
```php
Route::resource('admin.products', 'Admin\ProductsController');
```
It then expects an argument to be passed into `admin` in the form of 
```/admin/{admin}/product```

Therefore, name grouping is not possible and can cause confusion when having to omit the parent name from the sub-name.

**Comment by dgoring** [comment]
using resource with dot notation is **not** for namespacing its for sub-resources
i.e. 

```php
Route::resource('users.products', 'ProductsController');
```
this would be for "products" that belong to the user
/users/23/products

if you want prefixing you need to specify via the options, ideally via a group function
```php
Route::group([
  'prefix' => 'admin', // prefix the url path
  'namespace' => 'Admin',  // prefix the namespace for controller
  'as' => 'admin.' // prefix the route names auto generated within the group
], function () {
  Route::resource('products', 'ProductsController');
});
```

**Comment by daryn-staxo** [comment]
Understood :D
You learn something new everyday.

The issue in my code has been resolved.
I was unaware of the ``'as'`` option
Many Thanks
